# Generated by Django 5.0.7 on 2026-08-31 13:43

import django.db.models.deletion
from django.db import migrations, models

import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        default=game.models._generate_room_id,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("mode", models.CharField(default="STANDARD", max_length=20)),
                ("status", models.CharField(default="WAITING", max_length=20)),
                ("seed", models.CharField(default="", max_length=200)),
                ("host_id", models.CharField(default="", max_length=100)),
                ("max_players", models.IntegerField(default=4)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField()),
                ("event_type", models.CharField(max_length=50)),
                ("player_id", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("is_connected", models.BooleanField(default=True)),
                ("is_host", models.BooleanField(default=False)),
                ("hero_id", models.CharField(blank=True, default="", max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "player_id")},
            },
        ),
    ]
