# Generated by Django 5.0.7 on 2026-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_player_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="connection_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="gameevent",
            constraint=models.UniqueConstraint(
                fields=("session", "seq"), name="uniq_event_seq_per_session"
            ),
        ),
    ]
