# Generated by Django 5.0.7 on 2026-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_gamesession_kicked_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
