# Generated by Django 5.0.7 on 2026-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_gamesession_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityStat",
            fields=[
                (
                    "achievement_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("reporters", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
