# Generated by Django 5.0.7 on 2026-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_session_turn_clock"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="deck_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="hero_face",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
