# Generated by Devin on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_player_deck_id_player_hero_face"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="custom_deck_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
