# Generated by Django 5.0.7 on 2026-09-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_player_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField()),
                ("revision", models.IntegerField(default=0)),
                ("state", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-seq"],
            },
        ),
    ]
