# Generated by Django 5.2.17 on 2026-09-28 10:32

from django.db import migrations, models


def _backfill_cid(apps, schema_editor):
    """Rellena la columna cid desde data.cid en eventos existentes.

    Sin el backfill, un reintento de un cid procesado ANTES de la
    migración no lo encontraría en la columna y volvería a llamar al
    runner (cuya dedup cubre el caso — pero la columna debe quedar
    consistente para la dedup atómica futura).
    """
    GameEvent = apps.get_model("game", "GameEvent")
    for ev in GameEvent.objects.filter(event_type="COMMAND").exclude(data__cid__isnull=True):
        cid = (ev.data or {}).get("cid")
        # Si dos filas comparten cid en la misma sesión (log
        # pre-constraint), la segunda rompería la constraint — la
        # dejamos sin columna (la primera gana la dedup).
        if isinstance(cid, str) and cid and not GameEvent.objects.filter(session_id=ev.session_id, cid=cid).exists():
            GameEvent.objects.filter(pk=ev.pk).update(cid=cid)


def _clear_cid(apps, schema_editor):
    GameEvent = apps.get_model("game", "GameEvent")
    GameEvent.objects.update(cid=None)


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_gamesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameevent",
            name="cid",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.RunPython(_backfill_cid, _clear_cid),
        migrations.AddConstraint(
            model_name="gameevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cid__isnull", False)),
                fields=("session", "cid"),
                name="uniq_event_cid_per_session",
            ),
        ),
    ]
