# Generated by Django 5.2.17 on 2026-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_gameevent_cid_gameevent_uniq_event_cid_per_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="is_connected",
            field=models.BooleanField(default=False),
        ),
    ]
