# Generated by Django 5.2.17 on 2026-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_alter_player_is_connected"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="second_deck_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
