# Generated by Django 5.0.7 on 2026-09-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("card_type", models.CharField(max_length=20)),
                ("hero_class", models.CharField(blank=True, max_length=20, null=True)),
                ("copies", models.IntegerField(default=1)),
                ("printed_attack", models.IntegerField(blank=True, null=True)),
                ("printed_fortitude", models.IntegerField(blank=True, null=True)),
                ("printed_cost", models.IntegerField(blank=True, null=True)),
                ("effects", models.JSONField(default=list)),
                ("author", models.CharField(default="official", max_length=100)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CardVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.carddefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
