# Generated by Django 5.0.7 on 2026-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=16)),
                ("role", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=20)),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_id", models.CharField(max_length=200)),
                ("detail", models.JSONField(default=dict)),
                ("outcome", models.CharField(default="ok", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
