# Generated by Django 5.0.7 on 2026-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contentauditentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="carddefinition",
            name="owner_hash",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
